module mvconvert

import os

fn create_config_files(target_dir string) ! {

	md_file_path := os.join_path(target_dir,  "README.md")

	md_file_content := ('
	This directory contains Vlang files generated by meveo module converter
	in order to create tables or run the server exposing the API, you first need to set the environment variables
	by running the following command:
	\`\`\`
	source setConfig.sh
	\`\`\`
	Then you can run the following command to create the tables in the database:
	\`\`\`
	v run create_tables.v
	\`\`\`
	Finally, you can run the following command to start the server:
	\`\`\`
	v run server.v
	\`\`\`
	')
	os.write_file(md_file_path, md_file_content) or { return err }

	v_file_path := os.join_path(target_dir,  "setConfig.sh")

	file_content := ('
	export DB_HOST=localhost
	export DB_PORT=5432
	export DB_USER=postgres
	export DB_PASSWORD=postgres
	export DB_NAME=postgres
	')
	os.write_file(v_file_path, file_content) or { return err }
}
